/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementproject;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Unmatched TaiNguyen
 */
public class pnlClass extends javax.swing.JPanel {
    private final String urlList =frmMain.Ip + "/api/StudentManagement/GetListClass";
    private final String urlAdd =frmMain.Ip + "/api/StudentManagement/AddClasstAsync";
    private final String urlUpdate =frmMain.Ip + "/api/StudentManagement/UpdateClassAsync";
    private final String urlDelete =frmMain.Ip + "/api/StudentManagement/DeleteClassAsync";
    /**
     * Creates new form pnlClass
     */
    private final StudentManagementProject _SupportDb;

    public pnlClass() {
        initComponents();
        _SupportDb = new StudentManagementProject();

        Contructor();
    }
    private void Contructor (){
        String values = _SupportDb.ResquestGet(urlList);
        ObjectClass[] sts = _SupportDb.getJson().fromJson(values,ObjectClass[].class);
        
        MyTableModels<Student> myTableModels = new MyTableModels<>(new ArrayList(Arrays.asList(sts)));
        jTable2.setModel(myTableModels);
    }
  private JFrame _Myparent;

    public JFrame getMyparent() {
        return _Myparent;
    }

    public void setMyparent(JFrame _Myparent) {
        this._Myparent = _Myparent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        dlogObjectClass frmadd = new dlogObjectClass(_Myparent, true,null);
        frmadd.setVisible(true);
        if(frmadd.getObjectClass()!=null){
            int res =Integer.parseInt(_SupportDb.ResquestPost(urlAdd,frmadd.getObjectClass()));
            if(res<0) {
                JOptionPane.showMessageDialog(_Myparent, "Action Add Fail!");
            }else{
                String values = _SupportDb.ResquestGet(urlList);
                ObjectClass[] sts = _SupportDb.getJson().fromJson(values,ObjectClass[].class);

                MyTableModels<ObjectClass> myTableModels = new MyTableModels<>(new ArrayList(Arrays.asList(sts)));
                jTable2.setModel(myTableModels);
            }
        }
        frmadd.dispose();
                
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         //TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(_Myparent, "Please, Choose a Class!");
            return;
        }
        MyTableModels<ObjectClass> TableClass = (MyTableModels<ObjectClass>) jTable2.getModel();
        ObjectClass cl = TableClass.GetRow(row);
        dlogObjectClass frmadd = new dlogObjectClass(_Myparent, true,cl);
        frmadd.setVisible(true);
        if(frmadd.getObjectClass()!=null){
            int res =Integer.parseInt(_SupportDb.ResquestPost(urlUpdate,frmadd.getObjectClass()));
            if(res<0) {
                JOptionPane.showMessageDialog(_Myparent, "Action Update Fail!");
            }else{
                MyTableModels<ObjectClass> mytable = (MyTableModels<ObjectClass>) jTable2.getModel();
                mytable.fireTableDataChanged();
            }
        }
        frmadd.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(_Myparent, "Please, Choose a Class!");
            return;
        }
        MyTableModels<ObjectClass> Tablecl = (MyTableModels<ObjectClass>) jTable2.getModel();
        ObjectClass cl = Tablecl.GetRow(row);
        if(cl!=null){
            int ress = JOptionPane.showConfirmDialog(_Myparent,String.format("Are you sure Delete Class ID: %d, Name: %s",cl.getId(),cl.getName())
                ,"Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

            if(ress == JOptionPane.NO_OPTION) return;

            int res =Integer.parseInt(_SupportDb.ResquestPost(urlDelete,cl));
            if(res<0) {
                JOptionPane.showMessageDialog(_Myparent, "Action Update Fail!");
            }else{
                MyTableModels<ObjectClass> mytable = (MyTableModels<ObjectClass>) jTable2.getModel();
                mytable.RemoveRow(cl);
                mytable.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
