/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementproject;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Unmatched TaiNguyen
 */
public class pnlStudent extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final String urlList =frmMain.Ip + "/api/StudentManagement/GetListStudent";
    private final String urlAdd =frmMain.Ip + "/api/StudentManagement/AddStudent";
    private final String urlUpdate =frmMain.Ip + "/api/StudentManagemen"
            + "t/UpdateStudentAsync";
    private final String urlDelete =frmMain.Ip + "/api/StudentManagement/DeleteStudentAsync";

    private final StudentManagementProject _SupportDb;
    public pnlStudent() {
        initComponents();
       _SupportDb = new StudentManagementProject();

       Contructor();
    }
    private void Contructor (){
        String values = _SupportDb.ResquestGet(urlList);
        Student[] sts = _SupportDb.getJson().fromJson(values,Student[].class);
        
        MyTableModels<Student> myTableModels = new MyTableModels<>(new ArrayList(Arrays.asList(sts)));
        jTable1.setModel(myTableModels);
    }
    private JFrame _Myparent;

    public JFrame getMyparent() {
        return _Myparent;
    }

    public void setMyparent(JFrame _Myparent) {
        this._Myparent = _Myparent;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel2.add(btnDel);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        dlogAddStudent frmadd = new dlogAddStudent(_Myparent, true,null);
        frmadd.setVisible(true);
        if(frmadd.getStudent()!=null){
            int res =Integer.parseInt(_SupportDb.ResquestPost(urlAdd,frmadd.getStudent()));
            if(res<0) {
                JOptionPane.showMessageDialog(_Myparent, "Action Add Fail!");
            }else{
                String values = _SupportDb.ResquestGet(urlList);
                Student[] sts = _SupportDb.getJson().fromJson(values,Student[].class);
        
                MyTableModels<Student> myTableModels = new MyTableModels<>(new ArrayList(Arrays.asList(sts)));
                jTable1.setModel(myTableModels);
            }
        }
        frmadd.dispose();
//        JDialog dialog = new JDialog(this.getMyparent(),"",true);
//        dialog.getContentPane().add(frmadd.getContentPane());
//        dialog.pack();
//       // dialog.set(true);
//        JOptionPane.showConfirmDialog(jPanel1, "sdsdsd");
//        dialog.setVisible(true);
//        dialog.dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
         int row = jTable1.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(_Myparent, "Please, Choose a student!");
            return;
        }
        MyTableModels<Student> TableSt = (MyTableModels<Student>) jTable1.getModel();
        Student st = TableSt.GetRow(row);
        if(st!=null){
            int ress = JOptionPane.showConfirmDialog(_Myparent,String.format("Are you sure Delete Student ID: %d, Name: %s",st.getId(),st.getLastName()+" "+st.getFirstName())
            ,"Warning",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            
            if(ress == JOptionPane.NO_OPTION) return;
            
            int res =Integer.parseInt(_SupportDb.ResquestPost(urlDelete,st));
            if(res<0) {
                JOptionPane.showMessageDialog(_Myparent, "Action Update Fail!");
            }else{
                MyTableModels<Student> mytable = (MyTableModels<Student>) jTable1.getModel();
                mytable.RemoveRow(st);
                mytable.fireTableDataChanged();
            }
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(_Myparent, "Please, Choose a student!");
            return;
        }
        MyTableModels<Student> TableSt = (MyTableModels<Student>) jTable1.getModel();
        Student st = TableSt.GetRow(row);
        dlogAddStudent frmadd = new dlogAddStudent(_Myparent, true,st);
        frmadd.setVisible(true);
        if(frmadd.getStudent()!=null){
            int res =Integer.parseInt(_SupportDb.ResquestPost(urlUpdate,frmadd.getStudent()));
            if(res<0){
                JOptionPane.showMessageDialog(_Myparent, "Action Update Fail!");
            }else{
                MyTableModels<Student> mytable = (MyTableModels<Student>) jTable1.getModel();
                mytable.fireTableDataChanged();
            }
        }
        frmadd.dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
